### ISSUE TITLE
可以分享下代码高亮这部分的实现吗

### ISSUE THREAD

**Issue by F-loat** [phodal/code#4]
有在维护一个 wxparse 的 fork 版本，[mpvue-wxParse](https://github.com/F-loat/mpvue-wxParse)，前段时间有尝试过结合 highlight 和 prism，但是样式的问题会比较大，不确定是解析后的结构就有问题，还是只是目前的样式不合理，请问你这边主要是如何处理的呢

**Comment by phodal** [comment]
代码里不是有吗？你直接拿 git diff 一下 wxParse 目录就知道了。
